### ISSUE TITLE
"checkIsProcessTrusted" always returns false when move the App into "/Application" folder

### ISSUE THREAD

**Issue by wizardguy** [tmandry/AXSwift#18]
I just make a demo project basing on AXSwift. And found that if I launch the App directly from the Debug build or Archived App, it works as expected. But once I put the App into the /Application folder, the checkIsProcessTrusted always return false even I have enable the App in Accessiblity panel.

**Comment by tmandry** [comment]
You probably need to uncheck the app in the Accessibility panel, then re-check it. That has always worked for me when I've launched an app with the same name from different locations, and it's a weird quirk of the panel UI.

Let me know if this works.

**Comment by wizardguy** [comment]
Sorry for the late response. You're right. Simply re-check and check works for the "same name App from different locations". But it seems it does not work if I change the App bundle id. Anyway, everything works fine if I clear all the userdefaults and restart the Xcode & MacOS. I don't know what is root cause, but it seems that it should not be Swindler's issue.
