### ISSUE TITLE
Question on Licensing

### ISSUE THREAD

**Issue by ivanmoskalev** [tmandry/AXSwift#2]
Hello Tyler!

This is a very convenient little wrapper lib, very useful for a certain kind of apps! But it is a bit unclear at the moment what is the licensing for it – AFAIK it is something like copyright by default.

So the question is: did you intend it this way or you plan to release it under some permissive license (say, MIT)?

Thanks in advance!
cheers

**Comment by tmandry** [comment]
Added the MIT license – sorry for the delay in response.
