### ISSUE TITLE
How do I grant accessibility permission when debugging?

### ISSUE THREAD

**Issue by dexterleng** [tmandry/AXSwift#21]
Do you manually find the debug build and add it in the Security page?

**Comment by dexterleng** [comment]
ok figured out thats how you do it.

**Comment by filleokus** [comment]
@dexterleng: What solution did you come up with? Currently I'm checking and unchecking it in the Security page after each run, is there a better way?

**Comment by filleokus** [comment]
Oh, awesome! Thank you!
