### ISSUE TITLE
Error installing via SPM: Could not find AXSwift for arm64-apple-macos

### ISSUE THREAD

**Issue by rgbworld** [tmandry/AXSwift#34]
Xcode: 13.3
Swift: 5.6

After installing AXSwift via SPM, I  receive the following compiler error:
> Could not find module 'AXSwift' for target 'arm64-apple-macos'; found: x86_64-apple-macos

My research into the error indicates that building an `xcframework` for each architecture is the "new" way to distribute a framework that supports building & debugging on multiple architectures.

Should installation of AXSwift via SPM be working on M1? 
or does AXSwift need to be re-built as an `xcframework`?

Currently, I can build the AXSwift.framework locally and include it in project, but when Swift version is updated, I have to rebuild manually. I am hoping to modernize/automate that process via SPM.

How complicated is it to adapt AXSwift for multiple architectures? and is that something that is on the roadmap?

Thanks!

**Comment by tomaskupka** [comment]
Oh, I got the similar issue, but other way round. Have you found some solution for that? Thanks!

`Could not find module 'AXSwift' for target 'x86_64-apple-macos'; found: arm64-apple-macos,`

Runs well on M1 but won't compile for Intel.

**Comment by rgbworld** [comment]
Seems to work now. I am using AXSwift via SPM
