### ISSUE TITLE
Can't build AXSwiftExample: No such module 'AXSwift'

### ISSUE THREAD

**Issue by timbertson** [tmandry/AXSwift#6]
I'm _very_ new to xcode, so I may be barking up a number of the wrong trees. But I can't figure out how to get a project building which uses AXSwift, nor can I even get the included example to build.

I've built `AXSwift.framework` OK using XCode (both manually and via carthage). But when I try to compile AXSwiftExample (or a new project which I've added the `.framework` to), I get `No such module 'AXSwift'` on the `import AXSwift` line.

I've tried to learn how frameworks interact with swift modules, but to be honest I'm a bit lost. Most of the resources are just "how to do [specific thing] with xcode", rather than describing how modules actually work and how they interact with frameworks.

I've built other swift modules as frameworks though (my own simple example and also Alamofire), and notice that each of them have something in `Modules`:

```
$ ls Carthage/Build/Mac/Alamofire.framework/Versions/Current/Modules/
Alamofire.swiftmodule module.modulemap
```

But my built framework for axswift seems to have very little:

```
$ ls Carthage/Build/Mac/AXSwift.framework/Versions/Current/
AXSwift   Resources
```

`AXSwift` seems to be a shared object, so maybe I could link against it if I could get that far - but it seems to be missing the compile time `.modulemap`. Is this why XCode can't find the module? Have I built it wrong, or am I using it wrong?

**Comment by rgbworld** [comment]
I seem to be having the same issue. When I build the framework with the current release 0.2.0, I get an error: "No such module 'AXSwift'" when attempting to `import AXSwift`.

I am currently using an older version of AXSwift.framework and when I compare the directory structure of the 2 versions, it looks like there is a build issue. As you can see in the image below, the older AXSwift.framework is on the left and the new build is on the right. There are missing symlinks among other differences in the directory contents.

I could be building improperly as well, but when I put the older version back in my project, it builds and runs just fine.

![screen shot 2017-12-24 at 5 36 17 pm](https://user-images.githubusercontent.com/1319222/34329796-98f62d8e-e8d3-11e7-8e8c-484d5f916b22.png)


Thanks for the great framework.

**Comment by rgbworld** [comment]
I have corrected the issue locally. My solution was to remove the `Sources` directory from the Xcode project, rename the directory to 'AXSwift' then re-add it to the project, making sure to select 'Create groups' for 'Added Folders'. This caused the `.swift` files to be added to the 'Compile sources' section of the 'Build Phases' panel. They were previously missing. I then moved `AXSwift.h` from 'Project' to 'Public' on the 'Headers' build phase.

There may be a quicker or cleaner fix, but the underlying issue is that the files in the 'Sources` directory don't think they are part of the project and are not in the build phase. 

I am now successfully able to build the AXSwift.framework and use it in my project. Thanks again!

**Comment by tmandry** [comment]
Thanks for your report @timbertson, and thanks for your help @rgbworld! Currently I'm trying to juggle support on three different build/package systems (Xcode, CocoaPods, and SPM) and it's not easy unfortunately.

I've created a branch `fix-xcode-build` which should fix these issues. Please give it a try, and if it looks good I'll make a bugfix release.

**Comment by rgbworld** [comment]
Perfect build and import. Straight-out-of-the-box. Xcode 9.1, macOS 10.13.1

**Comment by timbertson** [comment]
Yep, worked great for me too - thanks 👍

**Comment by anandkumarpatel** [comment]
+1 your @tmandry your branch got teh build working, however, I can't seem to get the `.app` files to work? I there are no errors but the targes show red after a successful
<img width="242" alt="screen shot 2018-01-03 at 11 16 21 pm" src="https://user-images.githubusercontent.com/2194285/34553394-21acc6c8-f0dc-11e7-9889-ef242ef230ce.png">
 build

**Comment by natew** [comment]
I'm seeing the `no such module AXSwift` error when installing through SPM, with or without the branch. Is this related?
