### ISSUE TITLE
How to use `systemWideElement` to receive `.focusedUIElementChanged` notifications

### ISSUE THREAD

**Issue by acheronfail** [tmandry/AXSwift#9]
I'm a little unsure how to use AXSwift to observe changes to `NSAccessibilityFocusedUIElementChangedNotification`. Basically, I'd like to know when the user hovers over a dock icon.

I'm currently trying this to observe changes using the provided `systemWideElement`, but I think I may be using this incorrectly:

```swift
let app = Application(NSRunningApplication.current)
observer = app?.createObserver({ (observer, element, notification) in
    print("callback", (observer, element, notification))
})

do {
    try observer?.addNotification(.focusedUIElementChanged, forElement: systemWideElement)
} catch {
	// !!! This fails with AXError.InvalidUIElement
    print("notification: ", error)
}
```

How are we supposed to use the `systemWideElement` provided?

**Comment by acheronfail** [comment]
If I understand [Apple's example](https://developer.apple.com/library/content/samplecode/UIElementInspector/Introduction/Intro.html) correctly, I don't think you can observe these notifications, but rather have to loop and check them.

**Comment by tmandry** [comment]
I believe you can observe the notifications, but it has to be either at the application or window level, not system-wide. So you'd have to set notifications at the correct level and also keep track of which application and window is focused, etc.
